name: newtotolist
description: A new Flutter application.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore:
  firebase_core:
  flutter_native_splash: ^2.2.4

  flutter:
    sdk: flutter
  intl: ^0.17.0

  table_calendar: ^2.2.3
  flutter_slidable: ^0.5.7
  
  flutter_speed_dial: ^6.0.0
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  google_fonts:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20

flutter_native_splash:
  color: "##FCE09F"
  image: asset/image/aawake.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path_android: "asset/image/awake-icon.jpg"
  image_path_ios: "asset/image/awake-icon.jpg"


flutter:


  uses-material-design: true


  assets:
    - asset/image/
 
  fonts:
    - family: avenir
      fonts:
        - asset: asset/font/Avenir-Medium.ttf

